In [1]:
import sys,os
sys.path.append(os.pardir)
import numpy as np
from tensorflow.examples.tutorials.mnist import input_data
from PIL import Image
import tensorflow as tf

In [2]:
def trainNet():
    mnist = input_data.read_data_sets ("MNIST_data/", one_hot=True)
    x = tf.placeholder (tf.float32, [None, 784], name='X')
    W = tf.Variable (tf.zeros ([784, 10]),name="w")
    b = tf.Variable (tf.zeros ([10]),name="b")
    # Construct a linear model
    y = tf.nn.softmax (tf.matmul (x, W) + b, name="pred")
    y_ = tf.placeholder (tf.float32, [None, 10])
    keep_prob = tf.placeholder (tf.float32)
    # 定义测试的准确率
    correct_prediction = tf.equal (tf.argmax (y, 1), tf.argmax (y_, 1))
    accuracy = tf.reduce_mean (tf.cast (correct_prediction, tf.float32))
    #
    saver = tf.train.Saver (max_to_keep=1)
    max_acc = 0
    train_accuracy = 0
    #交叉熵
    cross_entropy = tf.reduce_mean (-tf.reduce_sum (y_ * tf.log (y)))
    # cross_error=cross_entropy_error_batch(y,y_)
    train_step = tf.train.GradientDescentOptimizer (0.01).minimize (cross_entropy)
    sess = tf.InteractiveSession ()
    tf.global_variables_initializer ().run ()
    for i in range (50):
        batch_xs, batch_ys = mnist.train.next_batch (100)
        sess.run (train_step, feed_dict={x: batch_xs, y_: batch_ys, keep_prob: 1.0})
        train_accuracy = accuracy.eval (feed_dict={x: batch_xs, y_: batch_ys, keep_prob: 1.0})
        print ("step %d, training accuracy %g" % (i, train_accuracy))
        saver.save (sess, './mnist_model/mnist_100.ckpt')
trainNet()

Instructions for updating:
Please use alternatives such as official/mnist/dataset.py from tensorflow/models.
Instructions for updating:
Please write your own downloading logic.
Instructions for updating:
Please use tf.data to implement this functionality.
Extracting MNIST_data/train-images-idx3-ubyte.gz
Instructions for updating:
Please use tf.data to implement this functionality.
Extracting MNIST_data/train-labels-idx1-ubyte.gz
Instructions for updating:
Please use tf.one_hot on tensors.
Extracting MNIST_data/t10k-images-idx3-ubyte.gz
Extracting MNIST_data/t10k-labels-idx1-ubyte.gz
Instructions for updating:
Please use alternatives such as official/mnist/dataset.py from tensorflow/models.
step 0, training accuracy 0.48
step 1, training accuracy 0.61
step 2, training accuracy 0.58
step 3, training accuracy 0.52
step 4, training accuracy 0.54
step 5, training accuracy 0.51
step 6, training accuracy 0.68
step 7, training accuracy 0.69
step 8, training accuracy 0.88
step 9, training accur

In [3]:
# import the inspect_checkpoint library
from tensorflow.python.tools import inspect_checkpoint as chkp
# print all tensors in checkpoint file
chkp.print_tensors_in_checkpoint_file(
    "./mnist_model/mnist_100.ckpt", tensor_name='', all_tensors=True)

tensor_name:  b
[-0.08864587  0.19907866 -0.03322526 -0.10384166  0.05253445  0.27046007
 -0.03096306  0.22740693 -0.4423793  -0.05042442]
tensor_name:  w
[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
# Total number of params: 7850


In [4]:
tensor_name_list = [tensor.name for tensor in tf.get_default_graph().as_graph_def().node]
#print(tensor_name_list)
for tensor_name in tensor_name_list:
    print(tensor_name,'\n')

X 

zeros/shape_as_tensor 

zeros/Const 

zeros 

w 

w/Assign 

w/read 

zeros_1 

b 

b/Assign 

b/read 

MatMul 

add 

pred 

Placeholder 

Placeholder_1 

ArgMax/dimension 

ArgMax 

ArgMax_1/dimension 

ArgMax_1 

Equal 

Cast 

Const 

Mean 

save/filename/input 

save/filename 

save/Const 

save/SaveV2/tensor_names 

save/SaveV2/shape_and_slices 

save/SaveV2 

save/control_dependency 

save/RestoreV2/tensor_names 

save/RestoreV2/shape_and_slices 

save/RestoreV2 

save/Assign 

save/Assign_1 

save/restore_all 

Log 

mul 

Const_1 

Sum 

Neg 

Const_2 

Mean_1 

gradients/Shape 

gradients/grad_ys_0 

gradients/Fill 

gradients/Mean_1_grad/Reshape/shape 

gradients/Mean_1_grad/Reshape 

gradients/Mean_1_grad/Const 

gradients/Mean_1_grad/Tile 

gradients/Mean_1_grad/Const_1 

gradients/Mean_1_grad/truediv 

gradients/Neg_grad/Neg 

gradients/Sum_grad/Reshape/shape 

gradients/Sum_grad/Reshape 

gradients/Sum_grad/Shape 

gradients/Sum_grad/Tile 

gradients/mul_grad/Shape 


In [ ]:
# ！！！不用这个！！！！
def predict(sess, inputs):
    #mnist = input_data.read_data_sets ("MNIST_data/", one_hot=True)
    #meta_path = './mnist_model/mnist_100.ckpt.meta'
    #model_path = './mnist_model/mnist_100.ckpt'    
    #saver = tf.train.import_meta_graph (meta_path)
    #saver.restore (sess, model_path)
    #graph = tf.get_default_graph ()
    #W = graph.get_tensor_by_name ("w:0")
    #b = graph.get_tensor_by_name ("b:0")
    #x = tf.placeholder (tf.float32, [None, 784])
    #y = tf.nn.softmax (tf.matmul (x, W) + b)
    #keep_prob = tf.placeholder (tf.float32)
    batch_xs, batch_ys=mnist.train.next_batch (100)
    one_img = batch_xs[0].reshape ((1, 784))
    one_num = batch_ys[0].reshape ((1, 10))
    temp = sess.run (y, feed_dict={x: one_img, keep_prob: 1.0})
    b = sess.run (tf.argmax (temp, 1))
    return str(b[0])

In [5]:
def predict(sess, inputs):
    # n = len(inputs)
    file= open('/root/code/ZhouYY/inputs.txt', 'w')  
    for fp in inputs:
        file.write(str(fp))
        file.write('\n')
    file.close()
    preds = sess.run('pred:0', feed_dict={'X:0': np.array(inputs).reshape(1,-1)})
    
    # `X` is used, it must be defined in the model with that name explicitly!
    return [float(0) for p in preds]

In [6]:
sess = tf.Session ()

inputs = list()
mnist = input_data.read_data_sets ("MNIST_data/", one_hot=True)
batch_xs, batch_ys=mnist.train.next_batch (100)
one_img = batch_xs[0].reshape ((-1)) # (,784)
inputs.append(list(one_img))
print(len(inputs))
inp = one_img.tolist()
inp2 = np.array(inp).reshape(1,-1)
print(inp2.shape)


Extracting MNIST_data/train-images-idx3-ubyte.gz
Extracting MNIST_data/train-labels-idx1-ubyte.gz
Extracting MNIST_data/t10k-images-idx3-ubyte.gz
Extracting MNIST_data/t10k-labels-idx1-ubyte.gz
1
(1, 784)


In [7]:
from clipper_admin import ClipperConnection, DockerContainerManager
from clipper_admin.deployers.tensorflow import deploy_tensorflow_model
clipper_conn = ClipperConnection(DockerContainerManager())
clipper_conn.start_clipper()
clipper_conn.connect()

20-03-26:20:00:28 INFO     [docker_container_manager.py:184] [default-cluster] Starting managed Redis instance in Docker
20-03-26:20:00:33 INFO     [docker_container_manager.py:276] [default-cluster] Metric Configuration Saved at /tmp/tmpau19roqu.yml
20-03-26:20:00:34 INFO     [clipper_admin.py:162] [default-cluster] Clipper is running
20-03-26:20:00:34 INFO     [clipper_admin.py:172] [default-cluster] Successfully connected to Clipper cluster at localhost:1337


In [8]:
# Add an application with a name and an input type
clipper_conn.register_application(
    name="mnist-zyy", input_type="floats", 
    default_output="-1.0", slo_micros=10000000)

20-03-26:20:00:36 INFO     [clipper_admin.py:236] [default-cluster] Application mnist-zyy was successfully registered


In [ ]:
clipper_conn.get_all_apps()

In [ ]:
clipper_conn.get_all_models()

In [9]:
deploy_tensorflow_model(
    clipper_conn,
    name="mnist-zyy",
    version=1,
    input_type="floats",
    func=predict,
    tf_sess_or_saved_model_path="/root/code/ZhouYY/mnist_model/")

20-03-26:20:00:40 INFO     [deployer_utils.py:41] Saving function to /tmp/tmpl7v5gmpaclipper
20-03-26:20:00:40 INFO     [deployer_utils.py:51] Serialized and supplied predict function
20-03-26:20:00:40 INFO     [tensorflow.py:264] TensorFlow model copied to: tfmodel 
20-03-26:20:00:40 INFO     [tensorflow.py:277] Using Python 3.6 base image
20-03-26:20:00:40 INFO     [clipper_admin.py:534] [default-cluster] Building model Docker image with model data from /tmp/tmpl7v5gmpaclipper
20-03-26:20:00:41 INFO     [clipper_admin.py:539] [default-cluster] Step 1/2 : FROM clipper/tf36-container:0.4.1
20-03-26:20:00:41 INFO     [clipper_admin.py:539] [default-cluster]  ---> 3db42af800ff
20-03-26:20:00:41 INFO     [clipper_admin.py:539] [default-cluster] Step 2/2 : COPY /tmp/tmpl7v5gmpaclipper /model/
20-03-26:20:00:41 INFO     [clipper_admin.py:539] [default-cluster]  ---> 56a9b24941ae
20-03-26:20:00:41 INFO     [clipper_admin.py:539] [default-cluster] Successfully built 56a9b24941ae
20-03-26:20:0

In [10]:
clipper_conn.link_model_to_app(
    app_name="mnist-zyy",
    model_name="mnist-zyy")

20-03-26:20:00:50 INFO     [clipper_admin.py:303] [default-cluster] Model mnist-zyy is now linked to application mnist-zyy


In [11]:
query_address = clipper_conn.get_query_addr()
print(query_address)

localhost:1337


In [12]:
import requests, json, numpy as np
class NpEncoder(json.JSONEncoder):
    def default(self, obj):
        if isinstance(obj, np.integer):
            return int(obj)
        elif isinstance(obj, np.floating):
            return float(obj)
        elif isinstance(obj, np.ndarray):
            return obj.tolist()
        else:
            return super(NpEncoder, self).default(obj)

headers = {"Content-type": "application/json"}
requests.post("http://"+query_address+"/mnist-zyy/predict", 
              headers=headers, data=json.dumps({"input":one_img.tolist()})).json()

{'query_id': 0,
 'output': -1.0,
 'default': True,
 'default_explanation': 'Failed to retrieve a prediction response within the specified latency SLO'}

In [ ]:
clipper_conn.unlink_model_from_app('mnist-zyy','mnist-zyy')

In [ ]:
clipper_conn.get_all_apps()

In [ ]:
clipper_conn.stop_inactive_model_versions('mnist-zyy')

In [ ]:
clipper_conn.get_all_models()

In [ ]:
clipper_conn.delete_application('mnist-zyy')

In [13]:
clipper_conn.stop_all()

20-03-26:22:37:20 INFO     [clipper_admin.py:1424] [default-cluster] Stopped all Clipper cluster and all model containers
